version: '3.8'

services:
  skillmate-frontend:
    build:
      context: ../frontend/skillmate
      dockerfile: Dockerfile
    container_name: skillmate-frontend
    depends_on:
      - skillmate-backend
    ports:
      - "3000:3000"
  skillmate-db:
    image: postgres:15
    container_name: skillmate-db
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: skillmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - skillmate-db-data:/var/lib/postgresql/data

  skillmate-backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: skillmate-backend
    depends_on:
      - skillmate-db
      - skillmate-minio
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://skillmate-db:5432/skillmate}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${DB_SECRET:-the_biggest_secret_of_app_is_jwt_secret}
      APPLICATION_FRONTEND_URL: ${APPLICATION_FRONTEND_URL:-http://localhost:3000}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-210103040@stu.sdu.edu.kz}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-kwlr ynsa fgib pyyt}
      MINIO_URL: ${MINIO_URL:-http://213.109.146.203:9000}
    ports:
      - "8080:8080"

  skillmate-minio:
    image: minio/minio
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address :9090

  create-buckets:
    image: minio/mc
    depends_on:
      - skillmate-minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set minio http://skillmate-minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing minio/projectbucket;
      /usr/bin/mc anonymous set download minio/projectbucket;
      exit 0;
      "

volumes:
  skillmate-db-data:
