#Spring config
spring:
  application:
    name: skillmate-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

# JWT config
jwt:
  secret: ${JWT_SECRET:the_biggest_secret_of_app_is_jwt_secret}
  accessExpiration: 3600000
  refreshExpiration: 604800000

# Minio config
minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: projectbucket
  allowedTypes:
    allowedAchievementTypes: image/png,image/jpeg,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword
    allowedImageTypes: image/png,image/jpeg
  folders:
    profileImages: profile_images
    skillAchievements: skill_achievements
    adImages: ad_images
    chats: chats
    postImages: post_images
